(function () {
    'use strict';
    class SMAddonManager {
        constructor({ registry = window.SMAddonRegistry, storage = window.smAddonStorage } = {}) { this.registry = registry; this.storage = storage; this.initialized = false; this.instances = new Map(); this.status = new Map(); this.policy = { masterEnabled: true, safeMode: false, autoStart: true, allowExperimental: false, logLevel: 'info' }; }
        _emit(name, detail = {}) { window.dispatchEvent(new CustomEvent(name, { detail })); }
        _status(id, state, error = null) { const s = { state, error, changedAt: Date.now() }; this.status.set(id, s); this._emit('sm:addon-status-changed', { id, status: s }); return s; }
        init() { if (this.initialized) return this; this.initialized = true; this._emit('sm:addon-manager-ready', { manager: this }); if (this.policy.autoStart && this.policy.masterEnabled) this.enableConfigured(); return this; }
        setPolicy(key, value) { if (!(key in this.policy)) return value; this.policy[key] = value; if (key === 'masterEnabled') { if (!value) this.disableAll({ persist: false }); else if (this.initialized && this.policy.autoStart) this.enableConfigured(); } if (key === 'safeMode' && value) { for (const [id] of this.instances) { const e = this.registry.get(id); if (e && !e.manifest.builtIn) this.disable(id, { persist: false }); } } if (key === 'allowExperimental' && !value) { for (const [id] of this.instances) { const e = this.registry.get(id); if (e?.manifest?.experimental) this.disable(id, { persist: false }); } } this._emit('sm:addon-policy-changed', { key, value, policy: { ...this.policy } }); return value; }
        _canEnable(m) { if (!this.policy.masterEnabled) return { ok: false, reason: 'Add-ons are globally disabled.' }; if (this.policy.safeMode && !m.builtIn) return { ok: false, reason: 'Safe Mode only permits built-in add-ons.' }; if (m.experimental && !this.policy.allowExperimental) return { ok: false, reason: 'Experimental add-ons are disabled.' }; return { ok: true }; }
        _desired(m) { const v = this.storage?.getAddonState?.(m.id)?.enabled; return typeof v === 'boolean' ? v : !!m.defaultEnabled; }
        async enable(id, { persist = true } = {}) { id = String(id); if (this.instances.has(id)) return this.instances.get(id).instance; const e = this.registry?.get?.(id); if (!e) throw new Error(`Unknown add-on "${id}".`); const gate = this._canEnable(e.manifest); if (!gate.ok) { this._status(id, 'blocked', gate.reason); return null; } this._status(id, 'starting'); const ctx = new window.SMAddonContext(this, e.manifest); try { const instance = (await e.factory(ctx, e.manifest)) || {}; if (typeof instance.onEnable === 'function') await instance.onEnable(); this.instances.set(id, { context: ctx, instance, manifest: e.manifest }); if (persist) this.storage?.setEnabled?.(id, true); this._status(id, 'enabled'); ctx.log('Enabled.'); return instance; } catch (err) { ctx.dispose(); this._status(id, 'error', err?.message || String(err)); ctx.log('Failed to enable.', 'error', err); return null; } }
        async disable(id, { persist = true } = {}) { id = String(id); const live = this.instances.get(id); if (live) { try { if (typeof live.instance?.onDisable === 'function') await live.instance.onDisable(); } catch (e) { live.context.log('Disable hook failed.', 'warn', e); } live.context.dispose(); this.instances.delete(id); } if (persist) this.storage?.setEnabled?.(id, false); this._status(id, 'disabled'); return true; }
        async restart(id) { const enabled = this.isEnabled(id); await this.disable(id, { persist: false }); return enabled ? this.enable(id, { persist: false }) : true; }
        async enableConfigured() { for (const e of this.registry?.list?.() || []) { if (this._desired(e.manifest)) await this.enable(e.manifest.id, { persist: false }); } }
        async enableDefaults() { for (const e of this.registry?.list?.() || []) { if (e.manifest.defaultEnabled) await this.enable(e.manifest.id); } }
        async disableAll({ persist = true } = {}) { for (const id of Array.from(this.instances.keys())) await this.disable(id, { persist }); }
        isEnabled(id) { return this.instances.has(String(id)); }
        getStatus(id) { return this.status.get(String(id)) || { state: this.isEnabled(id) ? 'enabled' : 'disabled', error: null }; }
        getPreference(id, key, fallback = null) { const e = this.registry.get(id); const d = e?.manifest?.preferences?.find(p => p.id === key); return this.storage?.getPreference?.(id, key, d ? d.default : fallback); }
        getPreferences(id) { const e = this.registry.get(id); if (!e) return {}; const o = {}; for (const p of e.manifest.preferences) o[p.id] = this.getPreference(id, p.id, p.default); return o; }
        setPreference(id, key, value) { const e = this.registry.get(id); const d = e?.manifest?.preferences?.find(p => p.id === key); if (!d) return value; let next = value; if (d.type === 'boolean') next = value === true || value === 'true' || value === 1 || value === '1'; else if (d.type === 'number') { const x = Number(value); next = Number.isFinite(x) ? x : Number(d.default) || 0; if (Number.isFinite(Number(d.min))) next = Math.max(Number(d.min), next); if (Number.isFinite(Number(d.max))) next = Math.min(Number(d.max), next); } else next = String(value ?? ''); this.storage?.setPreference?.(id, key, next); const live = this.instances.get(id); try { live?.instance?.onPreferenceChanged?.(key, next, this.getPreferences(id)); } catch (err) { live?.context?.log?.(`Preference "${key}" update failed.`, 'warn', err); } this._emit('sm:addon-preference-changed', { id, key, value: next }); return next; }
        async runCommand(id, commandId) { const live = this.instances.get(String(id)); if (!live) throw new Error(`Add-on "${id}" is not enabled.`); const fn = live.instance?.commands?.[commandId]; if (typeof fn !== 'function') throw new Error(`Add-on "${id}" has no command "${commandId}".`); try { return await fn(); } catch (e) { live.context.log(`Command "${commandId}" failed.`, 'error', e); throw e; } }
        describe(id) { const e = this.registry.get(id); if (!e) return null; return { ...e.manifest, enabled: this.isEnabled(id), status: this.getStatus(id), preferences: this.getPreferences(id) }; }
        list() { return (this.registry?.list?.() || []).map(e => this.describe(e.manifest.id)); }
        debug() { console.table(this.list().map(a => ({ id: a.id, name: a.name, enabled: a.enabled, state: a.status?.state, category: a.category, version: a.version }))); }
    }
    window.SMAddonManagerClass = SMAddonManager;
    window.SMAddonManager = window.SMAddonManager || new SMAddonManager();
})();