/**
 * VideoExportManager.js
 * Current-frame PNG export + real-time WebM canvas recorder.
 */
(function (global) {
    'use strict'; class VideoExportManager {
        constructor() { this.recorder = null; this.chunks = []; this._style(); } _style() { if (document.getElementById('ve-export-style')) return; const s = document.createElement('style'); s.id = 've-export-style'; s.textContent = `.vexp{color:var(--video-text)}.vexp-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.vexp-row{margin-bottom:8px}.vexp-row label{display:block;font-size:8px;color:var(--video-text-muted);margin-bottom:3px}.vexp-row select,.vexp-row input{width:100%;height:24px;background:var(--video-bg-0);border:1px solid var(--video-border);color:var(--video-text);box-sizing:border-box}.vexp-btn{height:27px;border:1px solid var(--video-border);background:var(--video-bg-2);color:var(--video-text-muted);cursor:pointer;font-size:8px}.vexp-btn.primary{border-color:var(--video-accent);color:var(--video-text);background:color-mix(in srgb,var(--video-accent) 16%,var(--video-bg-2))}.vexp-btn:hover{color:var(--video-text);border-color:var(--video-accent)}.vexp-status{margin-top:8px;padding:7px;border:1px solid var(--video-border);background:var(--video-bg-0);font-size:8px;color:var(--video-text-soft);line-height:1.5}`; document.head.appendChild(s); } open() { const mgr = global.videoEditingManager; if (!mgr?.active) return; mgr.openTimelineToolDock?.('render'); setTimeout(() => { const host = mgr.getVideoToolPanelHost?.(); if (host) this.renderPanel(host, mgr); }, 0); } renderPanel(host, mgr = global.videoEditingManager) { if (!host) return; host.innerHTML = `<div class="vexp"><div class="vea-section-title" style="color:var(--video-accent);font-weight:700;font-size:10px;margin-bottom:8px">DELIVER / EXPORT</div><div class="vea-card"><div class="vexp-grid"><div class="vexp-row"><label>Format</label><select id="vexp-format"><option value="webm">WebM Video</option><option value="png">Current Frame PNG</option></select></div><div class="vexp-row"><label>FPS</label><input id="vexp-fps" type="number" min="1" max="120" value="${global.sequencerManager?.state?.fps || 30}"></div><div class="vexp-row"><label>Video Bitrate Mbps</label><input id="vexp-bitrate" type="number" min="1" max="50" step="1" value="8"></div><div class="vexp-row"><label>Resolution</label><input value="${mgr.resolution.w} × ${mgr.resolution.h}" disabled></div></div><div class="vexp-grid"><button class="vexp-btn" id="vexp-frame">Export Current Frame</button><button class="vexp-btn primary" id="vexp-record">Record Timeline WebM</button></div><div class="vexp-status" id="vexp-status">Ready. WebM export records the composition canvas in real time using the browser MediaRecorder encoder.</div></div></div>`; host.querySelector('#vexp-frame')?.addEventListener('click', () => this.exportFrame(mgr)); host.querySelector('#vexp-record')?.addEventListener('click', () => this.recordTimeline(mgr, host)); }
        _download(blob, name) { const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = name; document.body.appendChild(a); a.click(); setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 1000); } exportFrame(mgr) { mgr.renderCanvas?.(); mgr.canvas.toBlob(blob => { if (blob) this._download(blob, `SM-Engine-frame-${Date.now()}.png`); }, 'image/png'); }
        async recordTimeline(mgr, host) { if (this.recorder) { this.recorder.stop(); return; } const canvas = mgr.canvas; if (!canvas?.captureStream) return; const fps = Math.max(1, Number(host.querySelector('#vexp-fps')?.value) || 30), bitrate = Math.max(1, Number(host.querySelector('#vexp-bitrate')?.value) || 8) * 1e6; const stream = canvas.captureStream(fps); let mime = 'video/webm;codecs=vp9'; if (!MediaRecorder.isTypeSupported(mime)) mime = 'video/webm;codecs=vp8'; if (!MediaRecorder.isTypeSupported(mime)) mime = 'video/webm'; this.chunks = []; const rec = new MediaRecorder(stream, { mimeType: mime, videoBitsPerSecond: bitrate }); this.recorder = rec; const status = host.querySelector('#vexp-status'), button = host.querySelector('#vexp-record'); button.textContent = 'Stop Recording'; status.textContent = 'Recording timeline in real time…'; rec.ondataavailable = e => { if (e.data?.size) this.chunks.push(e.data); }; rec.onstop = () => { const blob = new Blob(this.chunks, { type: mime }); this._download(blob, `SM-Engine-export-${Date.now()}.webm`); stream.getTracks().forEach(t => t.stop()); this.recorder = null; button.textContent = 'Record Timeline WebM'; status.textContent = `Export complete • ${(blob.size / 1024 / 1024).toFixed(1)} MB`; }; rec.start(500); const seq = global.sequencerManager; if (seq) { seq.seekTo?.(seq.state.workStart || 0); if (!seq.state.playing) seq.play?.(); } }
    } global.VideoExportManager = VideoExportManager; global.veaExportEngine = global.veaExportEngine || new VideoExportManager();
})(window);