// engine/settings/system/SMHardwareInfo.js
(function () {
    'use strict';
    class SMHardwareInfo {
        constructor() { this._last = null; this._lastRenderer = null; }
        collect(renderer = window.renderer || null) { const nav = navigator || {}; const canvas = renderer?.domElement || document.querySelector('canvas'); const gl = renderer?.getContext?.() || canvas?.getContext?.('webgl2') || canvas?.getContext?.('webgl') || null; let gpuVendor = '', gpuRenderer = '', webglVersion = '', shadingLanguage = ''; try { if (gl) { const debugInfo = gl.getExtension?.('WEBGL_debug_renderer_info'); if (debugInfo) { gpuVendor = gl.getParameter(debugInfo.UNMASKED_VENDOR_WEBGL) || ''; gpuRenderer = gl.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL) || ''; } webglVersion = gl.getParameter?.(gl.VERSION) || ''; shadingLanguage = gl.getParameter?.(gl.SHADING_LANGUAGE_VERSION) || ''; } } catch { } const caps = renderer?.capabilities || {}; const info = { runtime: { userAgent: nav.userAgent || '', platform: nav.userAgentData?.platform || nav.platform || '', language: nav.language || '', online: nav.onLine !== false, crossOriginIsolated: self.crossOriginIsolated === true }, cpu: { logicalThreads: Number(nav.hardwareConcurrency || 0) }, memory: { deviceMemoryGB: Number(nav.deviceMemory || 0), jsHeapLimit: Number(performance?.memory?.jsHeapSizeLimit || 0), jsHeapUsed: Number(performance?.memory?.usedJSHeapSize || 0), jsHeapTotal: Number(performance?.memory?.totalJSHeapSize || 0) }, display: { devicePixelRatio: Number(window.devicePixelRatio || 1), screenWidth: Number(window.screen?.width || 0), screenHeight: Number(window.screen?.height || 0) }, graphics: { webgl2: typeof WebGL2RenderingContext !== 'undefined' && gl instanceof WebGL2RenderingContext, webgpu: !!nav.gpu, vendor: gpuVendor, renderer: gpuRenderer, webglVersion, shadingLanguage, maxTextureSize: Number(caps.maxTextureSize || 0), maxTextures: Number(caps.maxTextures || 0), maxVertexTextures: Number(caps.maxVertexTextures || 0), maxAnisotropy: Number(caps.getMaxAnisotropy?.() || 0), precision: caps.precision || '' }, renderer: { available: !!renderer, revision: window.THREE?.REVISION || '', calls: Number(renderer?.info?.render?.calls || 0), triangles: Number(renderer?.info?.render?.triangles || 0), geometries: Number(renderer?.info?.memory?.geometries || 0), textures: Number(renderer?.info?.memory?.textures || 0) }, storage: { indexedDB: 'indexedDB' in window, fileSystemAccess: typeof window.showDirectoryPicker === 'function' }, workers: { supported: typeof Worker !== 'undefined' }, timestamp: Date.now() }; this._last = info; this._lastRenderer = renderer; window.dispatchEvent(new CustomEvent('sm:system-hardware-info', { detail: { info } })); return info; }
        getLast() { return this._last || this.collect(window.renderer || null); }
        refresh() { return this.collect(window.renderer || this._lastRenderer || null); }
        formatBytes(bytes) { const value = Number(bytes) || 0; if (value <= 0) return 'Unknown'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; let amount = value, index = 0; while (amount >= 1024 && index < units.length - 1) { amount /= 1024; index++; } return `${amount.toFixed(index > 1 ? 2 : 0)} ${units[index]}`; }
        debug() { const info = this.refresh(); console.log('[SMHardwareInfo]', info); return info; }
    }
    const hardware = new SMHardwareInfo(); window.SMHardwareInfo = hardware; window.smHardwareInfo = hardware; window.SMHardwareInfoClass = SMHardwareInfo;
})();