// engine/settings/system/SMSystemSettingsManager.js
(function () {
    'use strict';
    class SMSystemSettingsManager {
        constructor() { this.state = { runtimeBackend: 'auto', backgroundWorkers: true, workerCount: 'auto', pauseHeavyTasksHidden: true, useIdleCallback: true, frameBudgetMs: 8, backgroundBudgetMs: 4, maxTasksPerFrame: 12, taskPriority: 'balanced', textureBudgetMB: 1024, geometryBudgetMB: 768, cacheBudgetMB: 512, autoResourceCleanup: true, unusedAssetTimeoutSec: 120, gpuDisposeDelayFrames: 3, shaderStrategy: 'background', shaderWarmupBudgetMs: 3, precompileVisibleMaterials: true, shaderCache: true, cachePolicy: 'balanced', cleanStaleCache: true, contextRecovery: true, crashSnapshot: '60', recoverySnapshots: 5, safeModeAfterCrash: true, diagnosticsLevel: 'standard', diagnosticsSamplingMs: 1000, trackLongTasks: true, trackAssetFailures: true, trackContextLoss: true }; this._initialized = false; this._contextLossBound = false; }
        init() { if (this._initialized) return this; this._initialized = true; this._applySubsystemConfig(); this._bindContextRecovery(); window.dispatchEvent(new CustomEvent('sm:system-settings-ready', { detail: { manager: this } })); return this; }
        set(key, value, options = {}) { if (!(key in this.state)) throw new Error(`Unknown system setting "${key}".`); const normalized = this._normalize(key, value); this.state[key] = normalized; this._applyKey(key, normalized); if (options.emit !== false) window.dispatchEvent(new CustomEvent('sm:system-setting-changed', { detail: { key, value: normalized } })); return normalized; }
        setMany(values, options = {}) { for (const [key, value] of Object.entries(values || {})) { if (key in this.state) this.set(key, value, { emit: false }); } this._applySubsystemConfig(); if (options.emit !== false) window.dispatchEvent(new CustomEvent('sm:system-settings-synchronized', { detail: this.getState() })); return this.getState(); }
        get(key) { return this.state[key]; }
        getState() { return { ...this.state }; }
        getHardwareInfo() { return window.SMHardwareInfo?.refresh?.() || null; }
        async getMemoryReport() { return await window.SMMemoryBudgetManager?.snapshot?.() || null; }
        async runMemoryCleanup() { const result = await window.SMMemoryBudgetManager?.cleanup?.('system-settings') || []; this.log(`Resource cleanup complete: ${result.length} hook(s) executed.`, 'info', result); return result; }
        async warmupScene() { const renderer = window.renderer, scene = window.scene, camera = window.activeCamera || window.camera; if (!renderer || !scene || !camera) throw new Error('Renderer, scene or active camera is missing.'); const start = performance.now(); if (typeof renderer.compileAsync === 'function') await renderer.compileAsync(scene, camera); else if (typeof renderer.compile === 'function') renderer.compile(scene, camera); else throw new Error('Renderer does not expose compile/compileAsync.'); const duration = performance.now() - start; this.log(`Shader warmup complete in ${duration.toFixed(1)} ms.`, 'info'); window.dispatchEvent(new CustomEvent('sm:system-shader-warmup-complete', { detail: { duration } })); return duration; }
        requestShaderCacheClear() { window.dispatchEvent(new CustomEvent('sm:system-clear-shader-cache-requested')); this.log('Shader-cache clear request dispatched.', 'info'); }
        async getStorageEstimate() { try { const estimate = await navigator.storage?.estimate?.(); return { usage: Number(estimate?.usage || 0), quota: Number(estimate?.quota || 0) }; } catch { return { usage: 0, quota: 0 }; } }
        async requestPersistentStorage() { try { return Boolean(await navigator.storage?.persist?.()); } catch { return false; } }
        requestClearCache(scope = 'stale') { window.dispatchEvent(new CustomEvent('sm:system-cache-clear-requested', { detail: { scope, policy: this.state.cachePolicy } })); this.log(`Cache clear request dispatched (${scope}).`, 'info'); }
        createRecoverySnapshot() { const metadata = { project: window.SMProjectManager?.currentProject?.name || window.currentProject?.name || '', timestamp: Date.now(), scene: window.scene?.name || '', selectedObject: window.selectedObject?.uuid || null }; try { localStorage.setItem('sm-system-recovery-last', JSON.stringify(metadata)); } catch { } window.dispatchEvent(new CustomEvent('sm:system-recovery-snapshot-requested', { detail: { metadata, maxSnapshots: this.state.recoverySnapshots } })); this.log('Recovery snapshot requested.', 'info', metadata); return metadata; }
        resetSafeMode() { window.EngineSettings?.set?.('setting-addons-safe-mode', false); window.dispatchEvent(new CustomEvent('sm:system-safe-mode-reset')); this.log('Safe Mode reset requested.', 'info'); }
        async runDiagnostics() { const report = await window.SMSystemDiagnostics?.scan?.(); if (report) this.log(`System scan: ${report.counts.error} error(s), ${report.counts.warning} warning(s).`, report.counts.error ? 'error' : report.counts.warning ? 'warn' : 'info', report); return report; }
        copySystemInfo() { return window.SMSystemDiagnostics?.copySystemInfo?.() || ''; }
        log(message, level = 'info', extra = null) { const args = [message]; if (extra !== null && extra !== undefined) args.push(extra); if (window.SMConsolePanel?.push) { window.SMConsolePanel.push(level, args, { source: 'SystemSettings' }); return; } const fn = level === 'error' ? console.error : level === 'warn' ? console.warn : console.info; fn.apply(console, args); }
        debug() { console.log('[SMSystemSettingsManager]', this.getState(), window.SMWorkerPoolManager?.getStats?.(), window.SMMemoryBudgetManager?.lastReport); }
        _applySubsystemConfig() { window.SMWorkerPoolManager?.configure?.({ enabled: this.state.backgroundWorkers, workerCount: this.state.workerCount, pauseWhenHidden: this.state.pauseHeavyTasksHidden, useIdleCallback: this.state.useIdleCallback, frameBudgetMs: this.state.frameBudgetMs, backgroundBudgetMs: this.state.backgroundBudgetMs, maxTasksPerFrame: this.state.maxTasksPerFrame, priorityMode: this.state.taskPriority }); window.SMMemoryBudgetManager?.configure?.({ textureMB: this.state.textureBudgetMB, geometryMB: this.state.geometryBudgetMB, cacheMB: this.state.cacheBudgetMB, autoCleanup: this.state.autoResourceCleanup, unusedAssetTimeoutSec: this.state.unusedAssetTimeoutSec, gpuDisposeDelayFrames: this.state.gpuDisposeDelayFrames }); window.SMSystemDiagnostics?.configure?.({ level: this.state.diagnosticsLevel, sampleMs: this.state.diagnosticsSamplingMs, trackLongTasks: this.state.trackLongTasks, trackAssetFailures: this.state.trackAssetFailures, trackContextLoss: this.state.trackContextLoss }); }
        _applyKey(key, value) { const workerKeys = new Set(['backgroundWorkers', 'workerCount', 'pauseHeavyTasksHidden', 'useIdleCallback', 'frameBudgetMs', 'backgroundBudgetMs', 'maxTasksPerFrame', 'taskPriority']); const memoryKeys = new Set(['textureBudgetMB', 'geometryBudgetMB', 'cacheBudgetMB', 'autoResourceCleanup', 'unusedAssetTimeoutSec', 'gpuDisposeDelayFrames']); const diagnosticKeys = new Set(['diagnosticsLevel', 'diagnosticsSamplingMs', 'trackLongTasks', 'trackAssetFailures', 'trackContextLoss']); if (workerKeys.has(key) || memoryKeys.has(key) || diagnosticKeys.has(key)) this._applySubsystemConfig(); if (key === 'runtimeBackend') window.dispatchEvent(new CustomEvent('sm:system-runtime-backend-requested', { detail: { backend: value } })); }
        _bindContextRecovery() { if (this._contextLossBound) return; this._contextLossBound = true; document.addEventListener('webglcontextlost', event => { if (!this.state.contextRecovery) return; event.preventDefault?.(); this.log('WebGL context lost. Recovery mode is enabled.', 'warn'); }, true); document.addEventListener('webglcontextrestored', () => { if (!this.state.contextRecovery) return; this.log('WebGL context restored.', 'info'); window.dispatchEvent(new CustomEvent('sm:system-context-restored')); }, true); }
        _normalize(key, value) { const booleans = new Set(['backgroundWorkers', 'pauseHeavyTasksHidden', 'useIdleCallback', 'autoResourceCleanup', 'precompileVisibleMaterials', 'shaderCache', 'cleanStaleCache', 'contextRecovery', 'safeModeAfterCrash', 'trackLongTasks', 'trackAssetFailures', 'trackContextLoss']); if (booleans.has(key)) return Boolean(value); const numbers = new Set(['frameBudgetMs', 'backgroundBudgetMs', 'maxTasksPerFrame', 'textureBudgetMB', 'geometryBudgetMB', 'cacheBudgetMB', 'unusedAssetTimeoutSec', 'gpuDisposeDelayFrames', 'shaderWarmupBudgetMs', 'recoverySnapshots', 'diagnosticsSamplingMs']); if (numbers.has(key)) return Number(value); if (key === 'workerCount') return String(value) === 'auto' ? 'auto' : Math.max(1, Math.min(16, Math.round(Number(value) || 1))); return String(value); }
    }
    const manager = new SMSystemSettingsManager(); window.SMSystemSettingsManager = manager; window.smSystemSettingsManager = manager; window.SMSystemSettingsManagerClass = SMSystemSettingsManager; manager.init();
})();