(function () {
    class SMWaterEditor {
        constructor(scene, camera, renderer, options = {}) { this.scene = scene; this.camera = camera; this.renderer = renderer; this.controls = options.controls || window.controls || null; this.terrain = options.terrain || window.terrain || null; this.mode = 'idle'; this.type = 'river'; this.points = []; this.handles = []; this.pathLine = null; this.selectedHandle = null; this.dragging = false; this.raycaster = new THREE.Raycaster(); this.mouse = new THREE.Vector2(); this.onChange = () => { }; this.onStatus = () => { }; this._bound = false; this._handleGeo = new THREE.SphereGeometry(0.22, 12, 10); this._handleMat = new THREE.MeshBasicMaterial({ color: 0x56b8ff, depthTest: false, transparent: true, opacity: 0.95 }); this._selectedMat = new THREE.MeshBasicMaterial({ color: 0xffffff, depthTest: false }); this._lineMat = new THREE.LineBasicMaterial({ color: 0x56b8ff, transparent: true, opacity: 0.9, depthTest: false }); this.bind(); }
        setCamera(camera) { if (camera) this.camera = camera; }
        setTerrain(terrain) { this.terrain = terrain || null; }
        bind() { if (this._bound || !this.renderer?.domElement) return; this._bound = true; this._onPointerDown = e => this.pointerDown(e); this._onPointerMove = e => this.pointerMove(e); this._onPointerUp = e => this.pointerUp(e); this._onDblClick = e => this.doubleClick(e); this._onKeyDown = e => this.keyDown(e); this.renderer.domElement.addEventListener('pointerdown', this._onPointerDown); this.renderer.domElement.addEventListener('pointermove', this._onPointerMove); window.addEventListener('pointerup', this._onPointerUp); this.renderer.domElement.addEventListener('dblclick', this._onDblClick); document.addEventListener('keydown', this._onKeyDown); }
        unbind() { if (!this._bound) return; this._bound = false; this.renderer?.domElement?.removeEventListener('pointerdown', this._onPointerDown); this.renderer?.domElement?.removeEventListener('pointermove', this._onPointerMove); window.removeEventListener('pointerup', this._onPointerUp); this.renderer?.domElement?.removeEventListener('dblclick', this._onDblClick); document.removeEventListener('keydown', this._onKeyDown); }
        _setMouse(event) { const rect = this.renderer.domElement.getBoundingClientRect(); this.mouse.x = ((event.clientX - rect.left) / rect.width) * 2 - 1; this.mouse.y = -((event.clientY - rect.top) / rect.height) * 2 + 1; }
        _activeCamera() { return window.cameraSystem?.camera || window.camera || this.camera; }
        _hitTerrain(event) { this._setMouse(event); const cam = this._activeCamera(); if (!cam) return null; this.raycaster.setFromCamera(this.mouse, cam); const terrain = this.terrain || window.terrain; if (terrain) { terrain.updateMatrixWorld?.(true); const targets = Array.isArray(terrain) ? terrain : [terrain]; const hits = this.raycaster.intersectObjects(targets, true).filter(hit => !hit.object.userData?.isWater && !hit.object.userData?.isHelper); if (hits.length) return hits[0].point.clone(); } const plane = new THREE.Plane(new THREE.Vector3(0, 1, 0), 0); const out = new THREE.Vector3(); return this.raycaster.ray.intersectPlane(plane, out) ? out.clone() : null; }
        _hitHandle(event) { this._setMouse(event); const cam = this._activeCamera(); if (!cam) return null; this.raycaster.setFromCamera(this.mouse, cam); const hits = this.raycaster.intersectObjects(this.handles, false); return hits[0]?.object || null; }
        _suspendViewport() { if (this.controls) this.controls.enabled = false; if (window.transformControls) window.transformControls.detach(); window.isBrushActive = false; window.__smWaterEditing = true; }
        _resumeViewport() { if (this.controls) this.controls.enabled = true; window.__smWaterEditing = false; document.body.style.cursor = ''; }
        start(type = 'river', existingPoints = null) { this.cancel(false); this.type = String(type).toLowerCase(); this.mode = 'draw'; this._suspendViewport(); document.body.style.cursor = 'crosshair'; if (Array.isArray(existingPoints) && existingPoints.length) { this.points = existingPoints.map(p => p.clone()); this._rebuildHandles(); this._rebuildPath(); } this.onStatus(this.type === 'ocean' ? 'Click once to set the ocean center. Double-click or press Enter to finish.' : (this.type === 'lake' || this.type === 'pool' ? 'Click the terrain to place the closed water boundary. Double-click or press Enter to finish.' : 'Click the terrain to place water spline points. Double-click or press Enter to finish.')); this.onChange(this.points); }
        edit(points, type = 'river') { this.cancel(false); this.type = String(type).toLowerCase(); this.points = (points || []).map(p => p.clone()); this.mode = 'edit'; this._suspendViewport(); this._rebuildHandles(); this._rebuildPath(); this.onStatus('Edit water control points. Drag handles to reshape the water body.'); this.onChange(this.points); }
        finish() { if (this.mode === 'idle') return; this.mode = 'idle'; this.dragging = false; this.selectedHandle = null; this._resumeViewport(); this.onStatus('Water path ready.'); this.onChange(this.points); }
        cancel(clear = true) { this.dragging = false; this.selectedHandle = null; this.mode = 'idle'; this._resumeViewport(); if (clear) { this.points = []; this.clearVisuals(); this.onChange(this.points); } }
        clear() { this.points = []; this.clearVisuals(); this.onChange(this.points); this.onStatus('Path cleared.'); }
        undo() { if (!this.points.length) return; this.points.pop(); this._rebuildHandles(); this._rebuildPath(); this.onChange(this.points); }
        addPoint(point) { if (!point) return; if (this.type === 'ocean' && this.points.length) { this.points[0].copy(point); this._rebuildHandles(); this._rebuildPath(); this.onChange(this.points); return; } this.points.push(point.clone()); this._addHandle(point, this.points.length - 1); this._rebuildPath(); this.onChange(this.points); }
        pointerDown(event) { if (event.button !== 0 || this.mode === 'idle') return; event.preventDefault(); event.stopPropagation(); if (this.mode === 'edit') { const handle = this._hitHandle(event); if (handle) { this.selectedHandle = handle; this.dragging = true; handle.material = this._selectedMat; return; } } if (this.mode === 'draw') { const point = this._hitTerrain(event); if (point) this.addPoint(point); } }
        pointerMove(event) { if (this.mode !== 'edit' || !this.dragging || !this.selectedHandle) return; event.preventDefault(); const p = this._hitTerrain(event); if (!p) return; const index = this.selectedHandle.userData.waterPointIndex; if (index == null) return; this.points[index].copy(p); this.selectedHandle.position.copy(p).addScalar(0); this._rebuildPath(); this.onChange(this.points); }
        pointerUp() { if (!this.dragging) return; if (this.selectedHandle) this.selectedHandle.material = this._handleMat; this.dragging = false; this.selectedHandle = null; }
        doubleClick(event) { if (this.mode === 'draw') { event.preventDefault(); event.stopPropagation(); this.finish(); } }
        keyDown(event) { if (this.mode === 'idle') return; if (event.key === 'Enter') { event.preventDefault(); this.finish(); } else if (event.key === 'Escape') { event.preventDefault(); this.cancel(false); } else if ((event.ctrlKey && event.key.toLowerCase() === 'z') || event.key === 'Backspace') { event.preventDefault(); this.undo(); } }
        _addHandle(position, index) { const h = new THREE.Mesh(this._handleGeo, this._handleMat); h.position.copy(position); h.name = `SMWaterPoint_${index}`; h.renderOrder = 999; h.frustumCulled = false; h.userData.isSystemObject = true; h.userData.ignoreInHierarchy = true; h.userData.selectable = false; h.userData.waterPointIndex = index; this.scene.add(h); this.handles.push(h); }
        _rebuildHandles() { for (const h of this.handles) this.scene.remove(h); this.handles = []; this.points.forEach((p, i) => this._addHandle(p, i)); }
        _rebuildPath() { if (this.pathLine) { this.scene.remove(this.pathLine); this.pathLine.geometry?.dispose?.(); this.pathLine = null; } if (this.points.length < 2) return; let pts; if (this.type === 'river') pts = new THREE.CatmullRomCurve3(this.points, false, 'catmullrom', 0.35).getPoints(Math.max(24, this.points.length * 18)); else { pts = this.points.map(p => p.clone()); if (this.points.length >= 3) pts.push(this.points[0].clone()); } const g = new THREE.BufferGeometry().setFromPoints(pts); this.pathLine = new THREE.Line(g, this._lineMat); this.pathLine.name = 'SMWaterEditorPath'; this.pathLine.renderOrder = 998; this.pathLine.frustumCulled = false; this.pathLine.userData.isSystemObject = true; this.pathLine.userData.ignoreInHierarchy = true; this.scene.add(this.pathLine); }
        clearVisuals() { if (this.pathLine) { this.scene.remove(this.pathLine); this.pathLine.geometry?.dispose?.(); this.pathLine = null; } for (const h of this.handles) this.scene.remove(h); this.handles = []; }
        dispose() { this.cancel(true); this.clearVisuals(); this.unbind(); this._handleGeo?.dispose?.(); this._handleMat?.dispose?.(); this._selectedMat?.dispose?.(); this._lineMat?.dispose?.(); }
    }
    window.SMWaterEditor = SMWaterEditor;
})();
