// ============================================================================
// AdvancedTerrainPresets.js
// SM Engine - Production Terrain Preset Library
// Dynamic Presets tab + realistic geological recipes.
// Load AFTER NodeTerrainEditor.js and all advanced terrain node libraries.
// ============================================================================
(function(global){
'use strict';
const PRESETS=[
{id:'cinematic-alps',name:'Cinematic Alps',icon:'🏔️',tag:'REALISTIC',cost:'HIGH',desc:'Sharp tectonic ridges, deep drainage and natural talus. Strong hero terrain for open-world scenes.',recipe:'alps'},
{id:'norwegian-fjords',name:'Norwegian Fjords',icon:'🧊',tag:'GLACIAL',cost:'HIGH',desc:'High alpine relief shaped into broad glacial valleys with coastal finishing.',recipe:'fjords'},
{id:'river-kingdom',name:'River Kingdom',icon:'🏞️',tag:'HYDROLOGY',cost:'HIGH',desc:'Large drainage basins, carved river networks and broad alluvial lowlands.',recipe:'rivers'},
{id:'iceland-volcanic',name:'Iceland Volcanic Island',icon:'🌋',tag:'VOLCANIC',cost:'MED',desc:'Ocean island, volcanic cones, erosion channels and believable coastal shelves.',recipe:'iceland'},
{id:'grand-canyon',name:'Grand Canyon',icon:'🏜️',tag:'EROSION',cost:'HIGH',desc:'Layered plateau, fluvial incision, mesas and sedimentary strata.',recipe:'canyon'},
{id:'sahara-erg',name:'Sahara Erg',icon:'🌬️',tag:'DESERT',cost:'MED',desc:'Large wind-warped dune sea with secondary dune fields and aeolian carving.',recipe:'sahara'},
{id:'patagonia',name:'Patagonia Range',icon:'❄️',tag:'GLACIAL',cost:'HIGH',desc:'Tectonic mountain spine, glacial valleys, exposed ridges and debris aprons.',recipe:'patagonia'},
{id:'tropical-karst',name:'Tropical Karst',icon:'🌿',tag:'KARST',cost:'MED',desc:'Humid limestone landscape with tower karst, sinkholes and drainage erosion.',recipe:'karst'},
{id:'badlands-pro',name:'Utah Badlands',icon:'🪨',tag:'BADLANDS',cost:'MED',desc:'Dense rills, hoodoos, stepped strata and dry drainage morphology.',recipe:'badlands'},
{id:'moon-highlands',name:'Moon Highlands',icon:'🌑',tag:'PLANETARY',cost:'MED',desc:'Power-law crater field, tectonic faults and ancient highland relief.',recipe:'moon'},
{id:'rolling-highlands',name:'Rolling Highlands',icon:'🌄',tag:'NATURAL',cost:'LOW',desc:'Soft macro hills with subtle erosion. Ideal for forests, villages and gameplay spaces.',recipe:'highlands'},
{id:'coastal-cliffs',name:'Atlantic Cliffs',icon:'🌊',tag:'COASTAL',cost:'MED',desc:'Wind-beaten highlands terminating in beaches, wave-cut shelves and sea cliffs.',recipe:'coast'}];
function install(editor){
if(!editor)return editor;
editor.realisticTerrainPresets=PRESETS;
editor._presetQualityIterations=function(base){const samples=this.originalHeightData?.length||65536;const ratio=Math.max(.18,Math.min(1,65536/Math.max(1,samples)));return Math.max(1200,Math.round(base*ratio));};
editor._buildRecipe=function(recipe){
this.clearGraph({apply:false});
const add=(type,params,x,y)=>this._presetNode(type,params,x,y);
const link=(a,ap,b,bp)=>this.connectNodes(a.id,ap,b.id,bp,{updateUI:false,apply:false});
const finish=(node,x=1500)=>{const out=add('output.terrain',{},x,120);link(node,'height',out,'height');this.setOutput(out.id,'height',false);};
const hydro=n=>this._presetQualityIterations(n);
if(recipe==='alps'){const plate=add('generator.plateTectonics',{plates:9,continentalHeight:8,oceanDepth:10,boundaryWidth:30,collisionUplift:62,riftDepth:18,transformRoughness:9,macroNoise:.18},40,120);const fold=add('generator.orogeny',{amplitude:48,wavelength:92,angle:32,foldSharpness:2.6,warpStrength:38,secondaryFold:.28,upliftNoise:.24},320,120);const alpine=add('generator.alpine',{amplitude:54,frequency:.0043,octaves:7,ridgeSharpness:2.8,warpStrength:31,valleyDepth:.17},600,120);const stream=add('hydrology.streamPower',{iterations:8,erosionRate:.13,areaExponent:.48,slopeExponent:1.05,maxCutPerIteration:1.45,deposition:.12},880,120);const hydraulic=add('geology.hydraulic',{iterations:hydro(9000),maxLifetime:42,sedimentCapacity:4.3,depositSpeed:.24,erodeSpeed:.29,brushRadius:2,strength:.78},1160,120);const talus=add('geology.thermal',{iterations:5,talusAngle:35,rate:.21,strength:.8},1440,120);link(plate,'height',fold,'base');link(fold,'height',alpine,'base');link(alpine,'height',stream,'height');link(stream,'height',hydraulic,'height');link(hydraulic,'height',talus,'height');finish(talus,1720);}
else if(recipe==='fjords'){const alpine=add('generator.alpine',{amplitude:88,frequency:.0038,octaves:7,ridgeSharpness:2.4,warpStrength:46,valleyDepth:.2},40,120);const glacial=add('geology.glacial',{iterations:8,incision:3.4,widening:.78,valleyThreshold:.18,smoothing:.52,strength:.95},330,120);const stream=add('hydrology.streamPower',{iterations:6,erosionRate:.09,areaExponent:.5,slopeExponent:1,maxCutPerIteration:1.1,deposition:.16},620,120);const talus=add('geology.talusDeposit',{minSlope:29,maxSlope:52,amount:3.2,spread:.72,strength:.75},910,120);const coast=add('geology.coastal',{seaLevel:0,beachWidth:4,beachHeight:.8,cliffHeight:18,cliffWidth:7,waveCut:.62,strength:.9},1200,120);link(alpine,'height',glacial,'height');link(glacial,'height',stream,'height');link(stream,'height',talus,'height');link(talus,'height',coast,'height');finish(coast,1490);}
else if(recipe==='rivers'){const fbm=add('generator.fbm',{amplitude:24,frequency:.0027,octaves:6,lacunarity:2.03,gain:.5,warpStrength:28,warpFrequency:.0045},40,120);const alpine=add('generator.alpine',{amplitude:34,frequency:.0035,octaves:6,ridgeSharpness:2.2,warpStrength:22,valleyDepth:.14},320,120);const stream=add('hydrology.streamPower',{iterations:12,erosionRate:.16,areaExponent:.5,slopeExponent:1,maxCutPerIteration:1.55,deposition:.18},600,120);const river=add('hydrology.riverNetwork',{threshold:.028,width:3.4,depth:8.5,bankWidth:2.8,bankHeight:.6,smoothPasses:3,strength:.95},880,120);const alluvial=add('hydrology.alluvial',{flowThreshold:.022,lowSlope:.2,amount:3.8,spread:.75,strength:.9},1160,120);link(fbm,'height',alpine,'base');link(alpine,'height',stream,'height');link(stream,'height',river,'height');link(river,'height',alluvial,'height');finish(alluvial,1450);}
else if(recipe==='iceland'){const island=add('generator.island',{radiusX:190,radiusZ:158,height:48,coastFalloff:.16,coastNoise:.12,frequency:.0055,octaves:6,mountainStrength:.4,seaLevel:0},40,120);const volcano=add('generator.volcanicField',{volcanoes:6,minRadius:22,maxRadius:66,minHeight:24,maxHeight:88,craterRadius:.17,craterDepth:.24,calderaChance:.28,lavaRoughness:.1,strength:.95},320,120);const stream=add('hydrology.streamPower',{iterations:5,erosionRate:.1,maxCutPerIteration:1.25,deposition:.12},600,120);const hydraulic=add('geology.hydraulic',{iterations:hydro(6000),maxLifetime:36,sedimentCapacity:3.6,depositSpeed:.23,erodeSpeed:.26,brushRadius:2,strength:.58},880,120);const coast=add('geology.coastal',{seaLevel:0,beachWidth:6,beachHeight:1,cliffHeight:12,cliffWidth:8,waveCut:.58,strength:.85},1160,120);link(island,'height',volcano,'base');link(volcano,'height',stream,'height');link(stream,'height',hydraulic,'height');link(hydraulic,'height',coast,'height');finish(coast,1450);}
else if(recipe==='canyon'){const base=add('generator.fbm',{amplitude:18,frequency:.0024,octaves:5,warpStrength:18,warpFrequency:.004},40,120);const mesa=add('geology.mesaEscarpment',{stepHeight:17,capStrength:.72,cliffSharpness:.82,erosionNoise:.14,frequency:.0065,strength:.85},320,120);const strata=add('geology.strata',{layerThickness:5.5,strength:.42,dip:7,strike:28,warp:1.1,warpFrequency:.006,sharpness:.78},600,120);const stream=add('hydrology.streamPower',{iterations:13,erosionRate:.2,areaExponent:.54,slopeExponent:1.1,maxCutPerIteration:1.8,deposition:.08},880,120);const river=add('hydrology.riverNetwork',{threshold:.024,width:2.2,depth:10.5,bankWidth:1.5,bankHeight:.25,smoothPasses:2,strength:.88},1160,120);link(base,'height',mesa,'height');link(mesa,'height',strata,'height');link(strata,'height',stream,'height');link(stream,'height',river,'height');finish(river,1450);}
else if(recipe==='sahara'){const base=add('generator.fbm',{amplitude:2.2,frequency:.0016,octaves:3,warpStrength:8,warpFrequency:.003},40,120);const dunes=add('generator.dunes',{height:15,wavelength:42,angle:24,sharpness:3.2,warpStrength:21,warpFrequency:.009,secondaryScale:.38,secondaryAngle:34,noiseAmount:.12,strength:1},320,120);const wind=add('geology.windErosion',{angle:24,wavelength:48,carveDepth:2.8,ridgeHeight:1.4,sharpness:3.4,noise:.2,strength:.48},600,120);const thermal=add('geology.thermal',{iterations:3,talusAngle:31,rate:.16,strength:.5},880,120);link(base,'height',dunes,'base');link(dunes,'height',wind,'height');link(wind,'height',thermal,'height');finish(thermal,1160);}
else if(recipe==='patagonia'){const plate=add('generator.plateTectonics',{plates:8,boundaryWidth:26,collisionUplift:58,riftDepth:14,continentalHeight:7,oceanDepth:8},40,120);const alpine=add('generator.alpine',{amplitude:68,frequency:.0042,octaves:7,ridgeSharpness:2.7,warpStrength:34,valleyDepth:.18},320,120);const glacial=add('geology.glacial',{iterations:8,incision:3,widening:.7,valleyThreshold:.2,smoothing:.48,strength:.9},600,120);const talus=add('geology.talusDeposit',{minSlope:30,maxSlope:54,amount:4,spread:.74,strength:.82},880,120);link(plate,'height',alpine,'base');link(alpine,'height',glacial,'height');link(glacial,'height',talus,'height');finish(talus,1160);}
else if(recipe==='karst'){const island=add('generator.island',{radiusX:170,radiusZ:145,height:42,coastFalloff:.2,coastNoise:.17,mountainStrength:.28},40,120);const karst=add('geology.karst',{density:46,minRadius:4,maxRadius:17,depth:8.5,towerStrength:.4,noiseScale:.011,strength:.92},320,120);const hydraulic=add('geology.hydraulic',{iterations:hydro(5500),maxLifetime:34,sedimentCapacity:3.8,depositSpeed:.28,erodeSpeed:.24,brushRadius:2,strength:.52},600,120);const coast=add('geology.coastal',{seaLevel:0,beachWidth:7,beachHeight:1.2,cliffHeight:10,cliffWidth:7,waveCut:.42,strength:.72},880,120);link(island,'height',karst,'height');link(karst,'height',hydraulic,'height');link(hydraulic,'height',coast,'height');finish(coast,1160);}
else if(recipe==='badlands'){const fbm=add('generator.fbm',{amplitude:15,frequency:.003,octaves:5,warpStrength:14},40,120);const bad=add('generator.badlands',{amplitude:38,frequency:.0145,ridges:.8,drainage:.7,terraceHeight:5.2,terraceStrength:.46,warpStrength:20,strength:.94},320,120);const stream=add('hydrology.streamPower',{iterations:6,erosionRate:.1,maxCutPerIteration:1.1,deposition:.06},600,120);const strata=add('geology.strata',{layerThickness:4.7,strength:.34,dip:4,strike:18,warp:.7,sharpness:.82},880,120);link(fbm,'height',bad,'base');link(bad,'height',stream,'height');link(stream,'height',strata,'height');finish(strata,1160);}
else if(recipe==='moon'){const fbm=add('generator.fbm',{amplitude:14,frequency:.006,octaves:5,warpStrength:5},40,120);const crater=add('generator.craterField',{count:58,minRadius:2.5,maxRadius:42,depth:.34,rimHeight:.18,ejecta:.1,powerLaw:2.35,strength:1},320,120);const fault=add('generator.faults',{faults:18,displacement:1.8,falloff:16,decay:.94,strength:.65},600,120);link(fbm,'height',crater,'base');link(crater,'height',fault,'base');finish(fault,880);}
else if(recipe==='highlands'){const fbm=add('generator.fbm',{amplitude:16,frequency:.0033,octaves:5,lacunarity:2,gain:.48,warpStrength:18,warpFrequency:.005,strength:1},40,120);const stream=add('hydrology.streamPower',{iterations:4,erosionRate:.055,maxCutPerIteration:.65,deposition:.22,strength:.55},320,120);const thermal=add('geology.thermal',{iterations:3,talusAngle:38,rate:.16,strength:.45},600,120);link(fbm,'height',stream,'height');link(stream,'height',thermal,'height');finish(thermal,880);}
else if(recipe==='coast'){const fbm=add('generator.fbm',{amplitude:28,frequency:.0032,octaves:6,warpStrength:25,warpFrequency:.004},40,120);const wind=add('geology.windErosion',{angle:230,wavelength:55,carveDepth:2.2,ridgeHeight:1.1,sharpness:2.8,noise:.24,strength:.32},320,120);const coast=add('geology.coastal',{seaLevel:0,beachWidth:7,beachHeight:1.1,cliffHeight:16,cliffWidth:8,waveCut:.7,strength:.95},600,120);const stream=add('hydrology.streamPower',{iterations:4,erosionRate:.06,maxCutPerIteration:.7,deposition:.14,strength:.45},880,120);link(fbm,'height',wind,'height');link(wind,'height',coast,'height');link(coast,'height',stream,'height');finish(stream,1160);}
else return false;
this.invalidateAll();this.updateGraphUI();this.frameAllNodes();this.applyGraph();return true;
};
editor.applyAdvancedPreset=function(id){const preset=PRESETS.find(item=>item.id===id||item.recipe===id);if(!preset){console.warn('[Terrain Presets] Unknown preset:',id);return false;}return this._buildRecipe(preset.recipe);};
editor.renderAdvancedPresetLibrary=function(){
const host=document.getElementById('tne-presets');if(!host)return false;
host.innerHTML='<div class="tne-presets-header"><div><strong>Production Terrains</strong><span>Geology-driven starting points</span></div><span class="tne-preset-count">'+PRESETS.length+'</span></div><div class="tne-preset-grid"></div>';
const grid=host.querySelector('.tne-preset-grid');
PRESETS.forEach(p=>{const b=document.createElement('button');b.type='button';b.className='tne-preset-card';b.dataset.preset=p.id;b.innerHTML='<span class="tne-preset-icon">'+p.icon+'</span><span class="tne-preset-copy"><span class="tne-preset-top"><strong>'+p.name+'</strong><em>'+p.cost+'</em></span><small>'+p.desc+'</small><span class="tne-preset-tag">'+p.tag+'</span></span>';b.addEventListener('click',()=>{if(!editor.targetTerrain)console.warn('[Terrain Presets] No terrain target selected. Graph will still be created, but cannot deform terrain until setTarget() is called.');editor.applyAdvancedPreset(p.id);});grid.appendChild(b);});
return true;
};
editor.renderAdvancedPresetLibrary();
return editor;
}
global.SM_REALISTIC_TERRAIN_PRESETS=PRESETS;
global.installAdvancedTerrainPresets=install;
const previousEnsure=global.ensureTerrainNodeEditor;
if(typeof previousEnsure==='function'){global.ensureTerrainNodeEditor=function(...args){const editor=previousEnsure.apply(this,args);return install(editor);};}
if(global.terrainNodeEditor)install(global.terrainNodeEditor);
})(window);