// ============================================================================
// NodeTerrainEditor.js — SM Engine Terrain Node Editor Pro v2
// Typed multi-input DAG, caching, presets, serialization and terrain integration.
// ============================================================================
(function(global){
'use strict';
const NS=global.SMTerrainNodes,R=global.SMTerrainNodeRegistry;
if(!NS?.BaseTerrainNode||!R) throw new Error('[Terrain Nodes] Load core + libraries before NodeTerrainEditor.js');
const {TerrainMath:M,ValueType:T,createTerrainContext}=NS;
const PORT_COLOR={[T.HEIGHT]:'#4e9bff',[T.MASK]:'#a78bfa',[T.SCALAR]:'#e5a84b',[T.ANY]:'#94a3b8'};
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const cssEscape=s=>global.CSS?.escape?CSS.escape(String(s)):String(s).replace(/[^a-zA-Z0-9_-]/g,'\\$&');
class NodeTerrainEditor{
 constructor(options={}){
  this.nodes=[];this.connections=[];this.targetTerrain=null;this.originalHeightData=null;this.context=null;this.outputNodeId=null;this.outputPort='height';this.activeNode=null;
  this.panX=0;this.panY=0;this.zoom=1;this.draggedNodeId=null;this.dragOffsetX=0;this.dragOffsetY=0;this.isPanning=false;this.panStartX=0;this.panStartY=0;
  this.pendingConnection=null;this.currentMouseX=0;this.currentMouseY=0;this.cache=new Map();this.baseRevision=1;this.applyTimer=null;this.lastEvaluationMs=0;this.isApplying=false;
  this.useGlobalPaintMask=options.useGlobalPaintMask!==false;this.brush={size:8,strength:.35,mode:'paint',preview:null,painting:false};
  this.refreshDOMReferences();this.bindTabEvents();this.bindGraphEvents();this.bindCoreEvents();this.bindMaskEvents();this.buildNodePalette();
  console.log('✅ SM Terrain Node Editor Pro v2 initialized');
 }
 refreshDOMReferences(){this.panel=document.getElementById('terrain-node-panel')||this.panel;this.graphContainer=document.getElementById('node-graph-container')||this.graphContainer;this.paramsContainer=document.getElementById('node-params-container')||this.paramsContainer;if(this.graphContainer){this.graphContent=this.graphContainer.querySelector('#node-graph-content')||this.graphContent;this.connectionCanvas=this.graphContainer.querySelector('#node-connection-canvas')||this.connectionCanvas;}return !!this.graphContainer;}
 _ensureGraphSurface(){if(!this.graphContainer)return false;if(!this.connectionCanvas||!this.graphContent){this.graphContainer.innerHTML='<canvas id="node-connection-canvas" style="position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:2"></canvas><div id="node-graph-content" style="position:absolute;inset:0;transform-origin:0 0;will-change:transform;overflow:visible;z-index:3"></div><div class="tne-canvas-hud" style="position:absolute;right:10px;bottom:8px;z-index:5;pointer-events:none"><span><strong id="tne-hud-node-count">0</strong> NODES</span> · <span><strong id="tne-hud-zoom">100%</strong></span> · <span><strong id="tne-hud-ms">0ms</strong></span> · <span><strong id="tne-hud-output">BASE</strong></span></div>';this.graphContent=this.graphContainer.querySelector('#node-graph-content');this.connectionCanvas=this.graphContainer.querySelector('#node-connection-canvas');}this.resizeCanvas();return true;}
 resizeCanvas(){if(!this.graphContainer||!this.connectionCanvas)return;const dpr=Math.min(global.devicePixelRatio||1,2),w=Math.max(1,this.graphContainer.clientWidth),h=Math.max(1,this.graphContainer.clientHeight);this.connectionCanvas.width=Math.floor(w*dpr);this.connectionCanvas.height=Math.floor(h*dpr);this.connectionCanvas.style.width=w+'px';this.connectionCanvas.style.height=h+'px';this.connectionCanvas.getContext('2d').setTransform(dpr,0,0,dpr,0,0);this.drawConnections();}
 applyGraphTransform(){if(!this.graphContent)return;this.graphContent.style.transform=`translate(${this.panX}px,${this.panY}px) scale(${this.zoom})`;this.updateHUD();this.drawConnections();}
 frameAllNodes(){if(!this.graphContainer)return;if(!this.nodes.length){this.panX=0;this.panY=0;this.zoom=1;return this.applyGraphTransform();}const minX=Math.min(...this.nodes.map(n=>n.x)),minY=Math.min(...this.nodes.map(n=>n.y)),maxX=Math.max(...this.nodes.map(n=>n.x+260)),maxY=Math.max(...this.nodes.map(n=>n.y+180)),pad=100,w=Math.max(1,maxX-minX+pad*2),h=Math.max(1,maxY-minY+pad*2);this.zoom=Math.max(.35,Math.min(1.35,this.graphContainer.clientWidth/w,this.graphContainer.clientHeight/h));this.panX=(this.graphContainer.clientWidth-(maxX-minX)*this.zoom)/2-minX*this.zoom;this.panY=(this.graphContainer.clientHeight-(maxY-minY)*this.zoom)/2-minY*this.zoom;this.applyGraphTransform();}
 addNode(typeOrNode,pos=null,options={}){const n=typeof typeOrNode==='string'?R.create(typeOrNode,options.params||{}):typeOrNode;if(!n)return null;if(pos){n.x=Number(pos.x)||0;n.y=Number(pos.y)||0;}else{const p=this.activeNode||this.nodes[this.nodes.length-1];n.x=p?p.x+290:60;n.y=p?p.y:100;}this.nodes.push(n);if(options.autoConnect!==false)this._autoConnectNode(n);if(n.type==='output.terrain')this.setOutput(n.id,'height',false);else if(!this.outputNodeId){const port=this._getHeightOutputPort(n);if(port)this.setOutput(n.id,port,false);}this.activeNode=n;this.invalidateNode(n.id,true);this.updateGraphUI();this.selectNode(n);if(options.apply!==false)this.scheduleGraphApply();return n;}
 _autoConnectNode(node){for(const [inputName,inputSpec] of Object.entries(node.inputs||{})){for(const candidate of [...this.nodes].reverse()){if(candidate===node)continue;const out=this._findCompatibleOutput(candidate,inputSpec.type);if(out&&this.connectNodes(candidate.id,out,node.id,inputName,{updateUI:false,apply:false}))return;}}}
 removeNode(id){this.nodes=this.nodes.filter(n=>n.id!==id);this.connections=this.connections.filter(c=>c.fromNodeId!==id&&c.toNodeId!==id);this.cache.delete(id);if(this.outputNodeId===id){const f=[...this.nodes].reverse().find(n=>this._getHeightOutputPort(n));this.outputNodeId=f?.id||null;this.outputPort=f?this._getHeightOutputPort(f):'height';}if(this.activeNode?.id===id){this.activeNode=null;if(this.paramsContainer)this.paramsContainer.innerHTML='';}this.updateGraphUI();this.scheduleGraphApply();}
 connectNodes(fromNodeId,fromPort='height',toNodeId,toPort='height',options={}){if(fromNodeId===toNodeId)return false;const a=this.nodes.find(n=>n.id===fromNodeId),b=this.nodes.find(n=>n.id===toNodeId),os=a?.outputs?.[fromPort],is=b?.inputs?.[toPort];if(!a||!b||!os||!is)return false;if(is.type!==T.ANY&&os.type!==T.ANY&&is.type!==os.type){console.warn(`[Terrain Nodes] Type mismatch ${os.type} -> ${is.type}`);return false;}if(this._wouldCreateCycle(fromNodeId,toNodeId)){console.warn('[Terrain Nodes] Cycle rejected');return false;}this.connections=this.connections.filter(c=>!(c.toNodeId===toNodeId&&c.toPort===toPort));this.connections.push({fromNodeId,fromPort,toNodeId,toPort});this.invalidateNode(toNodeId,true);if(options.updateUI!==false)this.updateGraphUI();if(options.apply!==false)this.scheduleGraphApply();return true;}
 disconnectInput(toNodeId,toPort){const n=this.connections.length;this.connections=this.connections.filter(c=>!(c.toNodeId===toNodeId&&c.toPort===toPort));if(n!==this.connections.length){this.invalidateNode(toNodeId,true);this.updateGraphUI();this.scheduleGraphApply();return true;}return false;}
 _wouldCreateCycle(from,to){const out=new Map();for(const c of this.connections){if(!out.has(c.fromNodeId))out.set(c.fromNodeId,[]);out.get(c.fromNodeId).push(c.toNodeId);}if(!out.has(from))out.set(from,[]);out.get(from).push(to);const stack=[to],seen=new Set();while(stack.length){const id=stack.pop();if(id===from)return true;if(seen.has(id))continue;seen.add(id);for(const n of out.get(id)||[])stack.push(n);}return false;}
 _topologicalSort(required=null){const map=new Map(this.nodes.map(n=>[n.id,n])),deg=new Map(this.nodes.map(n=>[n.id,0])),out=new Map();for(const c of this.connections){if(!map.has(c.fromNodeId)||!map.has(c.toNodeId))continue;if(!out.has(c.fromNodeId))out.set(c.fromNodeId,[]);out.get(c.fromNodeId).push(c.toNodeId);deg.set(c.toNodeId,(deg.get(c.toNodeId)||0)+1);}const q=this.nodes.filter(n=>(deg.get(n.id)||0)===0),ordered=[];while(q.length){const n=q.shift();ordered.push(n);for(const id of out.get(n.id)||[]){const d=(deg.get(id)||0)-1;deg.set(id,d);if(d===0)q.push(map.get(id));}}if(ordered.length!==this.nodes.length)throw new Error('[Terrain Nodes] Graph cycle');return required?ordered.filter(n=>required.has(n.id)):ordered;}
 _collectRequired(id){const req=new Set(),incoming=new Map();for(const c of this.connections){if(!incoming.has(c.toNodeId))incoming.set(c.toNodeId,[]);incoming.get(c.toNodeId).push(c.fromNodeId);}const stack=id?[id]:[];while(stack.length){const n=stack.pop();if(req.has(n))continue;req.add(n);for(const p of incoming.get(n)||[])stack.push(p);}return req;}
 _findCompatibleOutput(node,type){for(const [name,s] of Object.entries(node.outputs||{}))if(type===T.ANY||s.type===T.ANY||s.type===type)return name;return null;}
 _getHeightOutputPort(node){return this._findCompatibleOutput(node,T.HEIGHT);}
 setOutput(id,port='height',update=true){const n=this.nodes.find(x=>x.id===id);if(!n||n.outputs?.[port]?.type!==T.HEIGHT)return false;this.outputNodeId=id;this.outputPort=port;if(update){this.updateGraphUI();this.scheduleGraphApply();}return true;}
 invalidateNode(id,desc=false){this.cache.delete(id);if(!desc)return;const out=new Map();for(const c of this.connections){if(!out.has(c.fromNodeId))out.set(c.fromNodeId,[]);out.get(c.fromNodeId).push(c.toNodeId);}const stack=[...(out.get(id)||[])],seen=new Set();while(stack.length){const n=stack.pop();if(seen.has(n))continue;seen.add(n);this.cache.delete(n);for(const c of out.get(n)||[])stack.push(c);}}
 invalidateAll(){this.cache.clear();}
 _resolveOutput(){let n=this.nodes.find(x=>x.id===this.outputNodeId);if(n&&n.outputs?.[this.outputPort]?.type===T.HEIGHT)return {node:n,port:this.outputPort};n=[...this.nodes].reverse().find(x=>this._getHeightOutputPort(x));if(!n)return null;const p=this._getHeightOutputPort(n);this.outputNodeId=n.id;this.outputPort=p;return {node:n,port:p};}
 _bypassNode(node,ctx,inputs){const r={};for(const [outName,outSpec] of Object.entries(node.outputs||{})){let value=null;for(const [inName,inSpec] of Object.entries(node.inputs||{}))if(inSpec.type===outSpec.type&&inputs[inName]!==undefined){value=inputs[inName];break;}if(value===null&&outSpec.type===T.HEIGHT)value=ctx.baseHeights;if(value===null&&outSpec.type===T.MASK)value=ctx.maskData;r[outName]=value instanceof Float32Array?new Float32Array(value):value;}return r;}
 evaluateGraph(){if(!this.targetTerrain||!this.originalHeightData)return null;this.context=createTerrainContext(this.targetTerrain,this.originalHeightData);const output=this._resolveOutput();if(!output)return {height:new Float32Array(this.originalHeightData),outputsByNode:new Map()};const required=this._collectRequired(output.node.id),ordered=this._topologicalSort(required),outputs=new Map(),signatures=new Map();
  for(const node of ordered){const inputs={},keys=[];for(const c of this.connections){if(c.toNodeId!==node.id)continue;const up=outputs.get(c.fromNodeId);if(!up)continue;inputs[c.toPort]=up[c.fromPort];keys.push(`${c.toPort}:${signatures.get(c.fromNodeId)||''}:${c.fromPort}`);}keys.sort();const sig=`${this.baseRevision}|${node.getSignature()}|${keys.join('|')}`,cached=this.cache.get(node.id);if(cached?.signature===sig){outputs.set(node.id,cached.outputs);signatures.set(node.id,sig);continue;}let result;try{result=node.enabled===false?this._bypassNode(node,this.context,inputs):node.evaluate(this.context,inputs);}catch(e){console.error(`[Terrain Nodes] ${node.name} failed`,e);result=this._bypassNode(node,this.context,inputs);}const normalized={};for(const [port,spec] of Object.entries(node.outputs||{})){const v=result?.[port];if((spec.type===T.HEIGHT||spec.type===T.MASK)&&!(v instanceof Float32Array&&v.length===this.context.count)){normalized[port]=spec.type===T.HEIGHT?new Float32Array(this.context.baseHeights):new Float32Array(this.context.count).fill(1);}else normalized[port]=v;}this.cache.set(node.id,{signature:sig,outputs:normalized});outputs.set(node.id,normalized);signatures.set(node.id,sig);}
  const selected=outputs.get(output.node.id),height=selected?.[output.port] instanceof Float32Array?new Float32Array(selected[output.port]):new Float32Array(this.context.baseHeights);return {height,outputsByNode:outputs};}
 applyGraph(){if(this.isApplying||!this.targetTerrain||!this.originalHeightData)return false;this.isApplying=true;const t0=performance.now();try{const r=this.evaluateGraph();if(!r?.height)return false;const base=this.originalHeightData,final=new Float32Array(r.height),mask=this.targetTerrain.userData?.maskData;if(this.useGlobalPaintMask&&mask?.length===final.length)for(let i=0;i<final.length;i++)final[i]=base[i]+(final[i]-base[i])*M.clamp01(mask[i]);this._writeHeights(final);this.targetTerrain.userData.heightData=new Float32Array(final);this.targetTerrain.userData.nodeGraph=this.serializeGraph();this.targetTerrain.userData.needsUpdate=true;this.lastEvaluationMs=performance.now()-t0;this.updateHUD();global.dispatchEvent(new CustomEvent('sm:terrain-node-applied',{detail:{terrain:this.targetTerrain,outputNodeId:this.outputNodeId,outputPort:this.outputPort,evaluationMs:this.lastEvaluationMs}}));return true;}finally{this.isApplying=false;}}
 _writeHeights(h){const terrain=this.targetTerrain,td=terrain.userData?.terrainData;if(td?.heights?.length===h.length){td.heights.set(h);td.version=(Number(td.version)||0)+1;const sx=this.context?.sizeX||1,sz=this.context?.sizeZ||1;terrain.userData?.componentManager?.updateRegion?.(0,sx-1,0,sz-1);global.dispatchEvent(new CustomEvent('sm:terrain-changed',{detail:{landscape:terrain}}));}else{const p=terrain.geometry?.attributes?.position;if(p?.count===h.length){for(let i=0;i<p.count;i++)p.setY(i,h[i]);p.needsUpdate=true;terrain.geometry.computeVertexNormals?.();terrain.geometry.computeBoundingBox?.();terrain.geometry.computeBoundingSphere?.();terrain.updateMatrixWorld?.(true);}}terrain.castShadow=true;terrain.receiveShadow=true;terrain.traverse?.(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});if(global.renderer?.shadowMap)global.renderer.shadowMap.needsUpdate=true;}
 scheduleGraphApply(delay=70){if(this.applyTimer)clearTimeout(this.applyTimer);this.applyTimer=setTimeout(()=>{this.applyTimer=null;this.applyGraph();},Math.max(0,delay));}
 setTarget(terrain){if(!terrain)return false;const td=terrain.userData?.terrainData,pos=terrain.geometry?.attributes?.position;if(!td?.heights&&!pos){console.warn('[Terrain Nodes] Unsupported terrain target');return false;}this.deactivatePaintMode();this.targetTerrain=terrain;global.terrain=terrain;let base;if(td?.heights)base=new Float32Array(td.heights);else{base=new Float32Array(pos.count);for(let i=0;i<pos.count;i++)base[i]=pos.getY(i);}this.originalHeightData=base;this.baseRevision++;this.invalidateAll();const ud=terrain.userData||(terrain.userData={});ud.nodeBaseHeights=new Float32Array(base);if(!ud.maskData||ud.maskData.length!==base.length)ud.maskData=new Float32Array(base.length).fill(1);this.context=createTerrainContext(terrain,base);if(ud.nodeGraph?.nodes?.length)this.restoreGraph(ud.nodeGraph,false);else{this.nodes=[];this.connections=[];this.outputNodeId=null;this.outputPort='height';this.activeNode=null;this.updateGraphUI();}if(this.panel)this.panel.style.display='flex';this.applyGraph();this.resizeCanvas();return true;}
 rebaseFromCurrentTerrain(){if(!this.targetTerrain)return false;const td=this.targetTerrain.userData?.terrainData,pos=this.targetTerrain.geometry?.attributes?.position;if(td?.heights)this.originalHeightData=new Float32Array(td.heights);else if(pos){this.originalHeightData=new Float32Array(pos.count);for(let i=0;i<pos.count;i++)this.originalHeightData[i]=pos.getY(i);}else return false;this.baseRevision++;this.invalidateAll();this.scheduleGraphApply(0);return true;}
 clearTarget(){this.deactivatePaintMode();this.targetTerrain=null;this.originalHeightData=null;this.context=null;this.invalidateAll();if(this.panel)this.panel.style.display='none';}
 serializeGraph(){return {version:2,outputNodeId:this.outputNodeId||null,outputPort:this.outputPort||'height',useGlobalPaintMask:this.useGlobalPaintMask,nodes:this.nodes.map(n=>n.serialize()),connections:this.connections.map(c=>({...c}))};}
 restoreGraph(state,apply=true){if(!state?.nodes||!Array.isArray(state.nodes))return false;const legacy={NoiseNode:'generator.fbm',RidgedNoiseNode:'generator.alpine',VoronoiCellsNode:'generator.voronoi',HydraulicErosionNode:'geology.hydraulic',SmoothNode:'geology.thermal',TerraceNode:'filter.quantize',HeightMaskNode:'mask.heightRange',NeutralTerrainPaintNode:'mask.paint'};const restored=[];for(const s of state.nodes){const type=R.has(s.type)?s.type:legacy[s.type];if(!type||!R.has(type)){console.warn(`[Terrain Nodes] Unknown saved node ${s.type}`);continue;}const n=R.create(type,s.params||{});n.id=s.id||n.id;n.name=s.name||n.name;n.enabled=s.enabled!==false;n.x=Number.isFinite(s.x)?s.x:60;n.y=Number.isFinite(s.y)?s.y:100;n.userData={...(s.userData||{})};restored.push(n);}this.nodes=restored;const ids=new Set(restored.map(n=>n.id));this.connections=[];for(const raw of state.connections||[]){const c={fromNodeId:raw.fromNodeId||raw.from,fromPort:raw.fromPort||'height',toNodeId:raw.toNodeId||raw.to,toPort:raw.toPort||'height'};if(ids.has(c.fromNodeId)&&ids.has(c.toNodeId))this.connectNodes(c.fromNodeId,c.fromPort,c.toNodeId,c.toPort,{updateUI:false,apply:false});}this.outputNodeId=ids.has(state.outputNodeId)?state.outputNodeId:(this.nodes[this.nodes.length-1]?.id||null);this.outputPort=state.outputPort||'height';if(typeof state.useGlobalPaintMask==='boolean')this.useGlobalPaintMask=state.useGlobalPaintMask;this.activeNode=null;this.invalidateAll();this.updateGraphUI();if(apply)this.applyGraph();return true;}
 clearGraph({apply=false}={}){this.nodes=[];this.connections=[];this.outputNodeId=null;this.outputPort='height';this.activeNode=null;this.invalidateAll();this.updateGraphUI();if(apply)this.applyGraph();}
 _presetNode(type,params,x,y){return this.addNode(type,{x,y},{params,autoConnect:false,apply:false});}
 applyPreset(name){this.clearGraph();const p=String(name||'mountains').toLowerCase();let chain=[];
  if(p==='desert'||p==='dunes')chain=[this._presetNode('generator.fbm',{amplitude:2,frequency:.002,octaves:3},50,120),this._presetNode('generator.dunes',{height:16,wavelength:38,angle:24,warpStrength:18},340,120),this._presetNode('geology.thermal',{iterations:3,talusAngle:31,rate:.18},630,120),this._presetNode('output.terrain',{},920,120)];
  else if(p==='island')chain=[this._presetNode('generator.island',{radiusX:185,radiusZ:150,height:62,mountainStrength:.8},50,120),this._presetNode('generator.alpine',{amplitude:24,frequency:.005,warpStrength:22,valleyDepth:.12},340,120),this._presetNode('geology.hydraulic',{iterations:10000,strength:.8},630,120),this._presetNode('geology.thermal',{iterations:4,strength:.75},920,120),this._presetNode('output.terrain',{},1210,120)];
  else if(p==='canyon')chain=[this._presetNode('generator.fbm',{amplitude:18,frequency:.0028,octaves:5},50,120),this._presetNode('generator.faults',{faults:18,displacement:3.5,falloff:22},340,120),this._presetNode('geology.hydraulic',{iterations:18000,sedimentCapacity:5,erodeSpeed:.38},630,120),this._presetNode('geology.strata',{layerThickness:6,dip:8,strength:.32},920,120),this._presetNode('output.terrain',{},1210,120)];
  else chain=[this._presetNode('generator.fbm',{amplitude:12,frequency:.003,octaves:5,warpStrength:20},50,120),this._presetNode('generator.alpine',{amplitude:92,frequency:.0042,warpStrength:42,valleyDepth:.2},340,120),this._presetNode('geology.hydraulic',{iterations:14000,brushRadius:2,erodeSpeed:.3},630,120),this._presetNode('geology.thermal',{iterations:5,talusAngle:34,rate:.22},920,120),this._presetNode('output.terrain',{},1210,120)];
  for(let i=0;i<chain.length-1;i++){const from=chain[i],to=chain[i+1],out=this._getHeightOutputPort(from),input=Object.entries(to.inputs||{}).find(([,s])=>s.type===T.HEIGHT)?.[0];if(out&&input)this.connectNodes(from.id,out,to.id,input,{updateUI:false,apply:false});}const last=chain[chain.length-1];if(last)this.setOutput(last.id,this._getHeightOutputPort(last)||'height',false);this.invalidateAll();this.updateGraphUI();this.frameAllNodes();this.applyGraph();return true;}
 selectNode(node){if(!node)return;this.activeNode=node;document.querySelectorAll('#node-graph-content .node-box').forEach(e=>e.classList.remove('selected'));document.getElementById(`node-${node.id}`)?.classList.add('selected');this.buildInspector(node);this.drawConnections();}
 buildInspector(node){if(!this.paramsContainer)return;const e=R.get(node.type),fields=Object.keys(node.params).map(k=>this._paramField(node,k,node.params[k],node.paramSchema?.[k]||{})).join('');this.paramsContainer.innerHTML=`<div class="tne-param-header" style="--node-color:${e?.color||'#43c58a'}"><span class="tne-param-icon"><i class="fas ${e?.icon||'fa-sliders-h'}"></i></span><span class="tne-param-title"><strong>${esc(node.name)}</strong><span>${esc(e?.role||node.type)}</span></span></div><div class="tne-param-list">${fields}</div>`;
  for(const k of Object.keys(node.params)){const s=node.paramSchema?.[k]||{},el=document.getElementById(`param-${node.id}-${k}`);if(!el)continue;const commit=ev=>{let v;if(s.type==='boolean')v=!!ev.target.checked;else if(s.type==='select')v=ev.target.value;else{v=Number(ev.target.value);if(!Number.isFinite(v))return;}node.params[k]=v;this.invalidateNode(node.id,true);this.scheduleGraphApply(ev.type==='input'&&s.type==='number'?90:0);};el.addEventListener(s.type==='select'||s.type==='boolean'?'change':'input',commit);if(s.type==='number')el.addEventListener('change',commit);}
  this.paramsContainer.querySelectorAll('[data-randomize-param]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.randomizeParam;node.params[k]=Math.floor(Math.random()*999999);this.invalidateNode(node.id,true);this.buildInspector(node);this.scheduleGraphApply(0);}));}
 _paramField(node,k,v,s){const label=esc(s.label||k.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())),id=`param-${node.id}-${k}`;if(s.type==='boolean'||typeof v==='boolean')return `<div class="tne-param-field"><label><span>${label}</span><input id="${id}" type="checkbox" ${v?'checked':''}></label></div>`;if(s.type==='select'){const opts=(s.options||[]).map(o=>`<option value="${esc(o)}" ${String(o)===String(v)?'selected':''}>${esc(o)}</option>`).join('');return `<div class="tne-param-field"><label><span>${label}</span><select id="${id}">${opts}</select></label></div>`;}const n=Number(v)||0,mag=Math.max(1,Math.abs(n)),min=s.min??-mag*4,max=s.max??mag*4,step=s.step??.01,rand=s.randomize?`<button type="button" data-randomize-param="${esc(k)}" title="Randomize">↻</button>`:'';return `<div class="tne-param-field"><label><span>${label}</span><span style="display:flex;gap:6px"><input id="${id}" type="number" min="${min}" max="${max}" step="${step}" value="${n}">${rand}</span></label></div>`;}
 updateGraphUI(){if(!this.graphContainer)this.refreshDOMReferences();if(!this._ensureGraphSurface())return;this.graphContent.innerHTML='';if(!this.nodes.length){this.graphContent.innerHTML='<div class="tne-empty-graph"><i class="fas fa-project-diagram"></i><strong>Empty Terrain Graph</strong><span>Add a generator to start.</span></div>';this.applyGraphTransform();return;}
  for(const n of this.nodes){const e=R.get(n.type),el=document.createElement('div');el.className='node-box sm-terrain-node-v2';el.id=`node-${n.id}`;el.style.cssText+=`position:absolute;left:${n.x}px;top:${n.y}px;min-width:240px;pointer-events:auto;--node-color:${e?.color||'#43c58a'}`;el.classList.toggle('selected',this.activeNode?.id===n.id);el.classList.toggle('is-output',this.outputNodeId===n.id);el.classList.toggle('is-bypassed',n.enabled===false);const ins=Object.entries(n.inputs||{}).map(([p,s])=>this._portHTML(n,p,s,'input')).join(''),outs=Object.entries(n.outputs||{}).map(([p,s])=>this._portHTML(n,p,s,'output')).join('');el.innerHTML=`<div class="node-header" data-node-drag-handle><span class="node-type-icon"><i class="fas ${e?.icon||'fa-circle-nodes'}"></i></span><span class="node-title-stack"><strong>${esc(n.name)}</strong><span>${esc(e?.role||n.type)}</span></span><span class="node-header-actions"><button class="node-output-btn ${this.outputNodeId===n.id?'active':''}" type="button"><i class="fas fa-bullseye"></i></button><button class="node-bypass-btn ${n.enabled===false?'active':''}" type="button"><i class="fas fa-power-off"></i></button><button class="node-remove-btn" type="button"><i class="fas fa-times"></i></button></span></div><div class="node-ports-wrapper"><div class="node-inputs">${ins}</div><div class="node-outputs">${outs}</div></div><div class="node-footer"><span>${esc(e?.category||n.category).toUpperCase()}</span><span>${esc(e?.cost||'MED')}</span></div>`;
   el.addEventListener('mousedown',ev=>{if(ev.target.closest('.node-header-actions')||ev.target.closest('.node-port'))return;this.selectNode(n);if(ev.target.closest('[data-node-drag-handle]')){const r=this.graphContent.getBoundingClientRect();this.draggedNodeId=n.id;this.dragOffsetX=(ev.clientX-r.left)/this.zoom-n.x;this.dragOffsetY=(ev.clientY-r.top)/this.zoom-n.y;ev.preventDefault();}ev.stopPropagation();});el.querySelector('.node-remove-btn')?.addEventListener('click',ev=>{ev.stopPropagation();this.removeNode(n.id);});el.querySelector('.node-bypass-btn')?.addEventListener('click',ev=>{ev.stopPropagation();n.enabled=n.enabled===false;this.invalidateNode(n.id,true);this.updateGraphUI();this.scheduleGraphApply(0);});el.querySelector('.node-output-btn')?.addEventListener('click',ev=>{ev.stopPropagation();const p=this._getHeightOutputPort(n);if(p)this.setOutput(n.id,p);});el.querySelectorAll('.node-port').forEach(p=>{p.addEventListener('click',ev=>{ev.stopPropagation();this._handlePortClick(p);});p.addEventListener('dblclick',ev=>{ev.stopPropagation();if(p.dataset.direction==='input')this.disconnectInput(p.dataset.nodeId,p.dataset.port);});});this.graphContent.appendChild(el);}
  this.applyGraphTransform();if(this.activeNode)this.buildInspector(this.activeNode);}
 _portHTML(n,p,s,dir){const color=PORT_COLOR[s.type]||'#94a3b8',connected=dir==='input'?this.connections.some(c=>c.toNodeId===n.id&&c.toPort===p):this.connections.some(c=>c.fromNodeId===n.id&&c.fromPort===p),dot=`<span class="node-port ${connected?'connected':''}" style="--port-color:${color}" data-node-id="${n.id}" data-port="${esc(p)}" data-port-type="${esc(s.type)}" data-direction="${dir}"></span>`,label=`<span class="node-port-label">${esc(p)}</span>`;return `<div class="node-port-row ${dir}">${dir==='input'?dot+label:label+dot}</div>`;}
 _handlePortClick(el){const d=el.dataset.direction;if(d==='output'){this.pendingConnection={fromNodeId:el.dataset.nodeId,fromPort:el.dataset.port,type:el.dataset.portType};return this.drawConnections();}if(d==='input'&&this.pendingConnection){const p=this.pendingConnection;this.pendingConnection=null;this.connectNodes(p.fromNodeId,p.fromPort,el.dataset.nodeId,el.dataset.port);}}
 _portElement(id,port,dir){return this.graphContent?.querySelector(`.node-port[data-node-id="${cssEscape(id)}"][data-port="${cssEscape(port)}"][data-direction="${dir}"]`)||null;}
 _portCenter(el,rect){const r=el.getBoundingClientRect();return{x:r.left-rect.left+r.width*.5,y:r.top-rect.top+r.height*.5};}
 _drawBezier(ctx,a,b,color,width,dashed=false){const dx=Math.max(45,Math.abs(b.x-a.x)*.45);ctx.save();ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.bezierCurveTo(a.x+dx,a.y,b.x-dx,b.y,b.x,b.y);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.globalAlpha=dashed?.75:.95;if(dashed)ctx.setLineDash([7,6]);ctx.stroke();ctx.restore();}
 drawConnections(){if(!this.connectionCanvas||!this.graphContainer)return;const ctx=this.connectionCanvas.getContext('2d'),rect=this.graphContainer.getBoundingClientRect();ctx.clearRect(0,0,this.graphContainer.clientWidth,this.graphContainer.clientHeight);for(const c of this.connections){const aEl=this._portElement(c.fromNodeId,c.fromPort,'output'),bEl=this._portElement(c.toNodeId,c.toPort,'input');if(!aEl||!bEl)continue;this._drawBezier(ctx,this._portCenter(aEl,rect),this._portCenter(bEl,rect),PORT_COLOR[aEl.dataset.portType]||'#94a3b8',2.3);}if(this.pendingConnection){const el=this._portElement(this.pendingConnection.fromNodeId,this.pendingConnection.fromPort,'output');if(el)this._drawBezier(ctx,this._portCenter(el,rect),{x:this.currentMouseX,y:this.currentMouseY},PORT_COLOR[this.pendingConnection.type]||'#94a3b8',1.8,true);}}
 updateHUD(){const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v;};set('tne-hud-node-count',this.nodes.length);set('tne-hud-zoom',Math.round(this.zoom*100)+'%');set('tne-hud-ms',this.lastEvaluationMs.toFixed(1)+'ms');const n=this.nodes.find(x=>x.id===this.outputNodeId);set('tne-hud-output',n?`${n.name}.${this.outputPort}`:'BASE');}
 switchTab(tabId){if(!this.panel)return false;const target=this.panel.querySelector(`#${CSS.escape(tabId)}`);if(!target)return false;this.panel.querySelectorAll('.tne-tab-panel').forEach(panel=>{panel.style.display='none';panel.classList.remove('tne-tab-panel-active');});target.style.display='flex';target.style.flexDirection='column';target.style.minHeight='0';target.classList.add('tne-tab-panel-active');this.panel.querySelectorAll('.tne-tab').forEach(button=>{const active=button.dataset.tab===tabId;button.classList.toggle('tne-tab-active',active);button.setAttribute('aria-selected',active?'true':'false');});if(this.paramsContainer)this.paramsContainer.style.display=tabId==='tne-nodes'?'flex':'none';if(tabId!=='tne-paint')this.deactivatePaintMode();if(tabId==='tne-presets')global.installAdvancedTerrainPresets?.(this);if(tabId==='tne-paint')this.refreshPaintUI();if(tabId==='tne-nodes')this.buildNodePalette(this._paletteQuery||'');return true;}
 bindTabEvents(){if(!this.panel)return false;if(this.panel.dataset.terrainTabsV2Bound==='1')return true;this.panel.dataset.terrainTabsV2Bound='1';this.panel.querySelectorAll('.tne-tab').forEach(button=>{button.type='button';button.setAttribute('role','tab');button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const tabId=button.dataset.tab;if(tabId)this.switchTab(tabId);});});const activeButton=this.panel.querySelector('.tne-tab.tne-tab-active')||this.panel.querySelector('.tne-tab[data-tab="tne-nodes"]')||this.panel.querySelector('.tne-tab');if(activeButton?.dataset?.tab)this.switchTab(activeButton.dataset.tab);return true;}
 buildNodePalette(query=''){const host=this.panel?.querySelector('#tne-nodes');if(!host)return;this._paletteQuery=String(query||'');let searchWrap=host.querySelector('.tne-palette-search');let searchInput=host.querySelector('#terrain-node-search');let list=host.querySelector('[data-tne-node-library-list]');if(!searchWrap||!searchInput||!list){host.innerHTML='';searchWrap=document.createElement('div');searchWrap.className='tne-palette-search';searchWrap.innerHTML='<i class="fas fa-search"></i><input id="terrain-node-search" type="search" placeholder="Search terrain operators" autocomplete="off" aria-label="Search terrain operators">';host.appendChild(searchWrap);list=document.createElement('div');list.className='tne-node-library-list';list.dataset.tneNodeLibraryList='1';host.appendChild(list);searchInput=searchWrap.querySelector('#terrain-node-search');searchInput.value=this._paletteQuery;searchInput.addEventListener('input',event=>this.buildNodePalette(event.target.value));}else if(searchInput.value!==this._paletteQuery){searchInput.value=this._paletteQuery;}const entries=R.search(this._paletteQuery),cats=R.getCategories();list.innerHTML='';for(const c of cats){const items=entries.filter(e=>e.category===c.id);if(!items.length)continue;const sec=document.createElement('div');sec.className='tne-node-category';sec.innerHTML=`<div class="tne-node-category-title" style="--cat-color:${c.color}"><i class="fas ${c.icon}"></i> ${esc(c.label)}<span class="tne-category-count">${items.length}</span></div>`;for(const e of items){const b=document.createElement('button');b.type='button';b.className='tne-node-btn';b.dataset.nodeType=e.type;b.style.setProperty('--node-color',e.color);b.innerHTML=`<i class="fas ${e.icon}"></i><span><strong>${esc(e.label)}</strong><small>${esc(e.role)}</small></span>`;b.addEventListener('click',()=>this.addNode(e.type));sec.appendChild(b);}list.appendChild(sec);}if(!entries.length){list.innerHTML='<div class="tne-library-empty"><i class="fas fa-search"></i><span>No terrain operators match this search.</span></div>';}}
 bindCoreEvents(){if(this._coreBound)return;this._coreBound=true;const bind=(id,ev,fn)=>document.getElementById(id)?.addEventListener(ev,fn);bind('node-apply-graph','click',()=>this.applyGraph());bind('node-frame-all','click',()=>this.frameAllNodes());bind('node-isolation-toggle','click',event=>{this.isolationActive=!this.isolationActive;this.toggleIsolation?.(this.isolationActive);event.currentTarget.classList.toggle('active',this.isolationActive);});bind('preset-mountains','click',()=>this.applyPreset('mountains'));bind('preset-hills','click',()=>this.applyPreset('mountains'));bind('preset-canyon','click',()=>this.applyPreset('canyon'));bind('preset-desert','click',()=>this.applyPreset('desert'));bind('preset-volcano','click',()=>{if(typeof this.applyAdvancedPreset==='function')this.applyAdvancedPreset('volcanic-island');else this.applyPreset('island');});bind('preset-moon','click',()=>{if(R.has('generator.craterField')){this.clearGraph({apply:false});const crater=this._presetNode('generator.craterField',{count:48,minRadius:3,maxRadius:38,depth:.36,rimHeight:.18},50,120);const fault=this._presetNode('generator.faults',{faults:14,displacement:1.5,falloff:18},340,120);const output=this._presetNode('output.terrain',{},630,120);this.connectNodes(crater.id,'height',fault.id,'base',{updateUI:false,apply:false});this.connectNodes(fault.id,'height',output.id,'height',{updateUI:false,apply:false});this.setOutput(output.id,'height',false);this.invalidateAll();this.updateGraphUI();this.frameAllNodes();this.applyGraph();}});global.addEventListener('resize',()=>this.resizeCanvas());}
 bindGraphEvents(){if(!this.graphContainer||this.graphContainer.dataset.terrainGraphV2Bound==='1')return;this.graphContainer.dataset.terrainGraphV2Bound='1';this.graphContainer.addEventListener('mousedown',e=>{const onNode=!!e.target.closest('.node-box'),pan=e.button===1||(e.button===0&&!onNode)||(e.button===0&&e.altKey);if(!pan)return;this.isPanning=true;this.panStartX=e.clientX-this.panX;this.panStartY=e.clientY-this.panY;e.preventDefault();});document.addEventListener('mousemove',e=>{if(this.graphContainer){const r=this.graphContainer.getBoundingClientRect();this.currentMouseX=e.clientX-r.left;this.currentMouseY=e.clientY-r.top;}if(this.isPanning){this.panX=e.clientX-this.panStartX;this.panY=e.clientY-this.panStartY;return this.applyGraphTransform();}if(this.draggedNodeId){const n=this.nodes.find(x=>x.id===this.draggedNodeId),r=this.graphContent?.getBoundingClientRect();if(!n||!r)return;n.x=(e.clientX-r.left)/this.zoom-this.dragOffsetX;n.y=(e.clientY-r.top)/this.zoom-this.dragOffsetY;const el=document.getElementById(`node-${n.id}`);if(el){el.style.left=n.x+'px';el.style.top=n.y+'px';}return this.drawConnections();}if(this.pendingConnection)this.drawConnections();});document.addEventListener('mouseup',()=>{this.isPanning=false;this.draggedNodeId=null;});this.graphContainer.addEventListener('wheel',e=>{e.preventDefault();const r=this.graphContainer.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,old=this.zoom,next=Math.max(.3,Math.min(2.2,old*(e.deltaY>0?.9:1.1))),wx=(mx-this.panX)/old,wy=(my-this.panY)/old;this.zoom=next;this.panX=mx-wx*next;this.panY=my-wy*next;this.applyGraphTransform();},{passive:false});this.graphContainer.addEventListener('contextmenu',e=>{if(this.pendingConnection){this.pendingConnection=null;this.drawConnections();e.preventDefault();}});}
 bindMaskEvents(){if(this._maskBound)return;this._maskBound=true;const paint=document.getElementById('node-paint-mask-btn'),erase=document.getElementById('node-erase-mask-btn'),clear=document.getElementById('node-clear-mask-btn'),size=document.getElementById('node-brush-size'),strength=document.getElementById('node-brush-strength');paint?.addEventListener('click',()=>this.togglePaintMode('paint'));erase?.addEventListener('click',()=>this.togglePaintMode('erase'));clear?.addEventListener('click',()=>{const mask=this.targetTerrain?.userData?.maskData;if(!mask){console.warn('[Terrain Nodes] Select a terrain before clearing its mask.');return;}mask.fill(0);this.invalidateAll();this.scheduleGraphApply(0);this.refreshPaintUI();global.dispatchEvent(new CustomEvent('sm:terrain-mask-changed',{detail:{terrain:this.targetTerrain}}));});size?.addEventListener('input',event=>{this.brush.size=Math.max(.1,Number(event.target.value)||8);this.updateBrushPreview();this.refreshPaintUI();});strength?.addEventListener('input',event=>{this.brush.strength=M.clamp01(Number(event.target.value)||0);this.refreshPaintUI();});const canvas=global.renderer?.domElement;if(canvas&&!canvas.dataset.terrainNodePaintV2Bound){canvas.dataset.terrainNodePaintV2Bound='1';canvas.addEventListener('pointerdown',event=>{if(!this.brush.preview?.visible)return;this.brush.painting=true;this._paintEvent(event);});canvas.addEventListener('pointerup',()=>this.brush.painting=false);canvas.addEventListener('pointerleave',()=>this.brush.painting=false);canvas.addEventListener('pointermove',event=>{if(!this.brush.preview?.visible)return;const hit=this._terrainHit(event);if(hit){this._positionBrush(hit);if(this.brush.painting)this._paintHit(hit);}});}this.refreshPaintUI();}
 refreshPaintUI(){const paint=document.getElementById('node-paint-mask-btn'),erase=document.getElementById('node-erase-mask-btn'),size=document.getElementById('node-brush-size'),strength=document.getElementById('node-brush-strength'),sizeValue=document.getElementById('node-brush-size-value'),strengthValue=document.getElementById('node-brush-strength-value');const active=!!this.brush.preview?.visible;paint?.classList.toggle('tne-paint-active',active&&this.brush.mode==='paint');erase?.classList.toggle('tne-paint-active',active&&this.brush.mode==='erase');if(size&&Math.abs(Number(size.value)-this.brush.size)>.001)size.value=String(this.brush.size);if(strength&&Math.abs(Number(strength.value)-this.brush.strength)>.001)strength.value=String(this.brush.strength);if(sizeValue)sizeValue.textContent=Number(this.brush.size).toFixed(2);if(strengthValue)strengthValue.textContent=Number(this.brush.strength).toFixed(2);}
 togglePaintMode(mode){if(this.brush.preview?.visible&&this.brush.mode===mode){this.deactivatePaintMode();return false;}return this.activatePaintMode(mode);}
 activatePaintMode(mode='paint'){if(!this.targetTerrain){console.warn('[Terrain Nodes] Select a terrain before entering mask paint mode.');return false;}this.brush.mode=mode;if(!this.brush.preview)this.createBrushPreview();this.brush.preview.visible=true;if(global.controls)global.controls.enabled=false;this.refreshPaintUI();return true;}
 deactivatePaintMode(){this.brush.painting=false;if(this.brush.preview)this.brush.preview.visible=false;if(global.controls)global.controls.enabled=true;this.refreshPaintUI();}
 createBrushPreview(){if(!global.THREE||!global.scene)return;const g=new THREE.Group();g.name='TerrainNodeMaskBrush';g.userData.isSystemObject=true;g.userData.excludeFromShadows=true;const m=new THREE.MeshBasicMaterial({color:0x38bdf8,transparent:true,opacity:.85,depthWrite:false,depthTest:false,side:THREE.DoubleSide}),ring=new THREE.Mesh(new THREE.RingGeometry(.94,1,64),m);ring.rotation.x=-Math.PI/2;ring.renderOrder=9999;g.add(ring);g.visible=false;global.scene.add(g);this.brush.preview=g;this.updateBrushPreview();}
 updateBrushPreview(){this.brush.preview?.scale.setScalar(this.brush.size);}
 _terrainHit(e){if(!this.targetTerrain||!global.renderer||!global.raycaster)return null;const rect=global.renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2(((e.clientX-rect.left)/rect.width)*2-1,-((e.clientY-rect.top)/rect.height)*2+1),cam=global.SMViewportSystem?.getActivePanel?.()?.camera||global.camera;if(!cam)return null;global.raycaster.setFromCamera(mouse,cam);return global.raycaster.intersectObject(this.targetTerrain,true)[0]||null;}
 _positionBrush(hit){this.brush.preview.position.copy(hit.point);this.brush.preview.position.y+=.025;this.updateBrushPreview();}
 _paintEvent(e){const h=this._terrainHit(e);if(h){this._positionBrush(h);this._paintHit(h);}}
 _paintHit(hit){if(!this.targetTerrain||!this.originalHeightData)return;const c=this.context||createTerrainContext(this.targetTerrain,this.originalHeightData),local=this.targetTerrain.worldToLocal(hit.point.clone()),cx=c.gridX(local.x),cz=c.gridZ(local.z),rx=Math.ceil(this.brush.size/Math.max(1e-6,c.cellSizeX)),rz=Math.ceil(this.brush.size/Math.max(1e-6,c.cellSizeZ)),minX=Math.max(0,Math.floor(cx-rx)),maxX=Math.min(c.sizeX-1,Math.ceil(cx+rx)),minZ=Math.max(0,Math.floor(cz-rz)),maxZ=Math.min(c.sizeZ-1,Math.ceil(cz+rz)),mask=this.targetTerrain.userData.maskData;for(let z=minZ;z<=maxZ;z++){const wz=c.worldZ(z);for(let x=minX;x<=maxX;x++){const wx=c.worldX(x),dx=wx-local.x,dz=wz-local.z,d=Math.sqrt(dx*dx+dz*dz);if(d>this.brush.size)continue;const fall=1-d/Math.max(1e-6,this.brush.size),amount=fall*this.brush.strength*.12,k=z*c.sizeX+x;mask[k]=M.clamp01(mask[k]+(this.brush.mode==='erase'?-amount:amount));}}this.invalidateAll();this.scheduleGraphApply(35);global.dispatchEvent(new CustomEvent('sm:terrain-mask-changed',{detail:{terrain:this.targetTerrain}}));}
}
global.NodeTerrainEditor=NodeTerrainEditor;NS.NodeTerrainEditor=NodeTerrainEditor;global.ensureTerrainNodeEditor=function(){if(global.terrainNodeEditor instanceof NodeTerrainEditor){global.terrainNodeEditor.refreshDOMReferences();global.terrainNodeEditor.bindTabEvents();global.terrainNodeEditor.bindGraphEvents();global.terrainNodeEditor.bindMaskEvents();global.terrainNodeEditor.buildNodePalette(global.terrainNodeEditor._paletteQuery||'');global.installAdvancedTerrainPresets?.(global.terrainNodeEditor);return global.terrainNodeEditor;}global.terrainNodeEditor=new NodeTerrainEditor();return global.terrainNodeEditor;};
})(window);
